### ISSUE TITLE
Admin CP User Edit Error 500

### ISSUE THREAD

**Issue by Ryatt** [hummingbird-me/hummingbird#195]
Attempting to "edit" any of the user fields by hitting the "edit" button in the admin cp returns a #500 error.

**Comment by cybrox** [comment]
I assume this has been resolved long time ago since last time I tried, it worked fine?

**Comment by NuckChorris** [comment]
It was "fixed" by Vikhyat removing all edit fields

**Comment by cybrox** [comment]
Will close this then, since it's not an active problem and 'advanced' user editing is not needed right now anyways, from what I can tell.
