### ISSUE TITLE
Linialomdil's Forum Bookmarks Broken?

### ISSUE THREAD

**Issue by NuckChorris** [hummingbird-me/hummingbird#202]
I'm *guessing* they had bookmarks in threads which died in The Great Forum Fuckup&trade;, but that's just a guess.  Most of the recent bugs have been related to violations of referential integrity caused by that.

http://forums.hummingbird.me/users/linialomdil/activity/bookmarks

**Comment by vevix** [comment]
Closing as this seems fixed, let us know if there is still an issue.
