### ISSUE TITLE
Break show more replies into chunks for display

### ISSUE THREAD

**Issue by btf064** [hummingbird-me/hummingbird#213]
**Issue**
Currently, when you hit <kbd>show more</kbd> for replies on post, it displays all replies. This can be an issue for posts with many replies (20+) as it can overwhelm the feed pushing other posts and the <kbd>show less</kbd> too far down.
**Solution**
Instead of displaying all replies when hitting <kbd>show more</kbd>,  a limited number more posts should be shown, and then if the user wants to they can hit <kbd>show more</kbd> to further display more replies.

**Comment by vevix** [comment]
Is this still an issue now that "Show more" is located above the replies always?

**Comment by NuckChorris** [comment]
I think it's still relevant. We should still break it into chunks for really big posts. We should also coalesce fanouts too, to improve big-post stuff. I think there's a middleware we can gem in for that. Our huge-post (>200 posts) support is pretty crap still.
