### ISSUE TITLE
Remaining feed functionality

### ISSUE THREAD

**Issue by JoshFabian** [hummingbird-me/hummingbird#311]
- [ ] Reposting
A user should be able to click a button on a post to share it on their own wall for their followers. It should be a literal 'mirror' of the original post, including total reposts and likes.

- [x] Onebox
Currently, a user has to link to the exact url of an image, this is confusing and often buggy. It would be ideal if we could utilize onebox within the feeds. This would improve embedding not only videos and images but articles and such as well, keeping the users on the feed where we can. We could later extend this to support oneboxing our own internal links. https://github.com/discourse/onebox

- [x] NSFW Posts
A user should be able to check a box on post submission to mark a post as nsfw. NSFW posts should behave in the same way that hentai pages do. Invisible to users with NSFW turned off as well as to guests. A picture of this functionality is included below. A user should not see the nsfw checkbox if they currently have nsfw content disabled.

- [ ] Anime & Manga linking
A user should be able to 'link' an anime to their post by typing it's name on the expanded submit post form. We should use some sort of typeahead to figure out what anime they're trying to tag. A picture of this functionality is included below.

![New post submission](http://cl.ly/image/3T242M1X0d1j/write-something.png)

Pending change, should give a general idea though.
![Linked anime](http://cl.ly/image/1Q1L3m3G0F42/hb-embed.png)

**Comment by cybrox** [comment]
NSFW posts will be implemented with #373
