### ISSUE TITLE
500 Error on Facebook Connect

### ISSUE THREAD

**Issue by NuckChorris** [hummingbird-me/hummingbird#329]
**Topic:** http://forums.hummingbird.me/t/500-internal-server-error-when-connecting-fb-to-hummingbird/18899

Apparently there's a regression in Facebook Connect.  Haven't reproduced.

**Comment by vikhyat** [comment]
afaik this only happens when you choose not to share your email with us. we should prompt them to enter an email when that happens, fairly large change.

**Comment by vevix** [comment]
Is it even possible to not share your email when we request it as required scope?
