### ISSUE TITLE
Cannot reorder Favorites

### ISSUE THREAD

**Issue by NuckChorris** [hummingbird-me/hummingbird#330]
**Thread:** http://forums.hummingbird.me/t/cant-edit-re-order-favourites/18755

This is evidently broken in two places by two different changes (ember-cli and JWT), so I expect the following tasks:

* [ ] Meet or remove dependency on jQuery UI
* [ ] Move favorites calls off APIv1

**Comment by cybrox** [comment]
Solution for this is working through #185
