### ISSUE TITLE
User about's panel its blank when not value. 

### ISSUE THREAD

**Issue by nivla** [hummingbird-me/hummingbird#345]
I think that the panel "About User" its must have a default value like "Nothing yet" rather than leave it blank the panel.
![screenshot-hummingbird me 2014-12-30 09-20-34](https://cloud.githubusercontent.com/assets/2448098/5578828/b38aa244-9005-11e4-9c9a-e2d584326f34.png)

**Comment by cybrox** [comment]
I don't think just filling in a default value here would make sense.
Guess the best solution would be still displaying it for the user itself with an info message to add some content and hide it for profile visitors.

**Comment by cybrox** [comment]
Fixed with #358
