### ISSUE TITLE
Access denied to cover image

### ISSUE THREAD

**Issue by fractalemagic** [hummingbird-me/hummingbird#346]
Heroku is being denied access to Melen's cover image.

Response body:

    <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>AccessDenied</Code><Message>Access Denied</Message>    
    <RequestId>4ED52BB74180A9FB</RequestId> 
    <HostId>5Py4+u0arqAipzx/p0Q93YA/SOZW+5uy36GmeZwycECNWkrS7SEfMsIh51/oHYElo2pyx2SxcJo=</HostId>
    </Error>

Response object:

    Response{protocol=http/1.1, code=403, message=Forbidden, url=https://static.hummingbird.me/users/cover_images/000/001/303/thumb/data.jpg?1415077431}

Works fine locally ¯\\_(ツ)_/¯

**Comment by vikhyat** [comment]
Does the exact same code work locally and not Heroku? No difference in terms of headers?

**Comment by fractalemagic** [comment]
Yeah they should be the same. It can load other cover images just fine, only seems to be broken for Melen AFAIK. This has actually been happening for a while, I just never got around to reporting it :expressionless:
