### ISSUE TITLE
Recurring Billing for PRO

### ISSUE THREAD

**Issue by vikhyat** [hummingbird-me/hummingbird#347]
How it's going to work is documented in this Gist: https://gist.github.com/vikhyat/ec0f4c27ed21b092ca12

Implementation checklist:

* [x] Add Sidetiq
* [x] Implement `ProMembershipManager#renew!`
* [x] Add hourly renewal job
* [x] Add daily retry job
* [x] Add non-recurring expiry upgrade to recurring nag email job
* [ ] Summon the Cthulhu

**Comment by NuckChorris** [comment]
>I will receive an email from Hummingbird if the charge is successful, and a different email every time charging my card fails.

Does this mean it should email every time it succeeds or just if a retry succeeds? /cc @JoshFabian ?
