### ISSUE TITLE
Ratings on unaired shows

### ISSUE THREAD

**Issue by skcihmit** [hummingbird-me/hummingbird#350]
Ratings on unaired shows bugs a lot of users.
Can an `{{#if IsAiring}}` be added around the right-side of https://github.com/hummingbird-me/hummingbird/blob/bbb58eb8a2c46cd327de8e8b3a9b47cb54b6cbe7/app/frontend/app/templates/anime/index.hbs ? I wanted to propose the change in the code but I'm not quite sure how to write a function for 'IsAiring' (or whatever would be more appropriate) to add to https://github.com/hummingbird-me/hummingbird/blob/bbb58eb8a2c46cd327de8e8b3a9b47cb54b6cbe7/app/frontend/app/controllers/anime/index.js

**Comment by vikhyat** [comment]
Just to be clear, are you referring to this?

![screen shot 2015-01-05 at 10 40 03 am](https://cloud.githubusercontent.com/assets/31063/5609471/403eb53e-94c7-11e4-80ba-444947610ea4.png)

`notYetAired` is already defined here: https://github.com/hummingbird-me/hummingbird/blob/master/app/frontend/app/models/anime.js#L76

You should be able to use `{{#unless notYetAired}}` to hide it for shows that have aired. PR would be welcome. :smile:

**Comment by skcihmit** [comment]
Yes, that's what I was referring to. Thanks, I'll go make that PR :)
