### ISSUE TITLE
New stuff needed for APIv2

### ISSUE THREAD

**Issue by vikhyat** [hummingbird-me/hummingbird#352]
* [ ] Get anime by season
* [ ] Network and airing time + day of week. We don't currently have this but TheTVDB exposes it, so we should start saving it

**Comment by nizlumina** [comment]
Great to see this! Currently I'm scraping parts of Hummingbird for this. Not a pretty solution so far. After hitting a bit of a stump with lots of the other anime-based-sites API for this feature, I really have to say (and humbly *stress*) that an official API for this is very much needed.

**Comment by NexPB** [comment]
Franchise anime ids would be helpfull as well.

**Comment by tunderdomb** [comment]
+1 I'd love to use it.
For reference: search by season, year of release, airing status (finished/airing/upcoming) would be a great addition to the API.

**Comment by DNA** [comment]
In this anime by season search, how would be the endpoint? I was thinking of something like `/anime/?season=fall&year=2015`

**Comment by NuckChorris** [comment]
I believe it would be `/api/v2/anime?query=params&in=here` where the query parameters are representative of the different fields.  The [JSONAPI](http://jsonapi.org/) spec may have something to say on the matter.

**Comment by DNA** [comment]
Yes, JSONAPI have a recomendation on this matter: [Recommendations for Filtering](http://jsonapi.org/recommendations/#filtering). Based on this, It would be like this:

    GET /anime?filter[season]=fall&filter[year]=2015

Can I work on this API search? Or is it task already taken? :)

**Comment by NuckChorris** [comment]
Feel free to take it.  If you have any questions you can hit up our Slack (email josh@hummingbird.me to get an invite) and we're all happy to help
