### ISSUE TITLE
Floating PRO section not usable below 760px viewport

### ISSUE THREAD

**Issue by wopian** [hummingbird-me/hummingbird#354]
Floating PRO section on the right is always fixed in the same position. This is fine for the common monitor heights, but any less than that (e.g `----x768` laptops) causes this section to be cut off - with no way of using it.

Following is at `612px` viewport height.

![](http://zippy.gfycat.com/AdventurousLimpAmphiuma.gif)

Forum thread: https://forums.hummingbird.me/t/pro-interface-wont-fit-on-screen/20004

**Comment by JoshFabian** [comment]
This would be the ideal solution to the problem: http://css-tricks.com/scroll-fix-content/
