### ISSUE TITLE
ember compiler

### ISSUE THREAD

**Issue by gzcarlos** [hummingbird-me/hummingbird#355]
After doing a `git clone` to this project I started the server, `rails s` and after following the wiki recommendations for Linux and Filling the Database, I got this error "ember-cli executable could not be found" after requesting the server. I just figured out that a **NPM** call will be needed, then I ran `npm install -g ember-cli` and then after starting the rails server again and loading the main page this came out: 
>Started GET "/" for 190.106.112.217 at 2015-01-08 13:38:53 +0000
>version: 0.1.5
>Could not find watchman, falling back to NodeWatcher for file system events
>BuildingBuilding...
>Cannot find module '/home/ubuntu/workspace/projects/bbucket/hummingbird/app/frontend/node_modules/broccoli-ember-hbs-template-compiler'
>Error: Cannot find module '/home/ubuntu/workspace/projects/bbucket/hummingbird/app/frontend/node_modules/broccoli-ember-hbs-template-compiler'
>    at Function.Module._resolveFilename (module.js:338:15)
>    at Function.Module._load (module.js:280:25)
>    at Module.require (module.js:364:17)
>    at require (module.js:380:17)
>    at requireLocal (/home/ubuntu/.nvm/v0.10.30/lib/node_modules/ember-cli/lib/utilities/require-local.js:6:10)
>    at TemplatePlugin.toTree (/home/ubuntu/.nvm/v0.10.30/lib/node_modules/ember-cli/lib/preprocessors/template-plugin.js:16:10)
>    at /home/ubuntu/.nvm/v0.10.30/lib/node_modules/ember-cli/lib/preprocessors.js:104:26
>   at Array.forEach (native)
>    at processPlugins (/home/ubuntu/.nvm/v0.10.30/lib/node_modules/ember-cli/lib/preprocessors.js:103:11)
>    at module.exports.preprocessTemplates (/home/ubuntu/.nvm/v0.10.30/lib/node_modules/ember-cli/lib/preprocessors.js:86:10)
>/? I’m about to timeout bringing down my unicorn worker too :(

well, after checking the route of the `npm install -g` for `ember-cli` there is no folder with the name **broccoli-ember-hbs-template-compiler**. I'm guessing I did a wrong `ember-cli` installation, so what should be the correct one for this project.

**Comment by cybrox** [comment]
From the steps you described, you might need to run `npm install` again in `[...]/app/frontend/`.
I don't know if that's what causes this particular error though.

**Comment by gzcarlos** [comment]
Solved, just did that.
