### ISSUE TITLE
Don't show user actions to guests on anime/manga pages

### ISSUE THREAD

**Issue by Wopian** [hummingbird-me/hummingbird#357]
![](https://i.imgur.com/GppH0EE.png?1)

At the moment it's visible, but changing it just throws a connection error alert.

*Will send PR once done with school.*

**Comment by Wopian** [comment]
Fixed in #361

**Comment by cybrox** [comment]
Speaking of disabling user actions, this might be something that could be implemented to the follow buttons as well.
I guess genereally hiding all the login required UI elements would make more sense than just throwing the user a `you need to be logged in` message.
Thoughts?

**Comment by vikhyat** [comment]
I think we should be showing a sign in modal instead of hiding half of our UI.
