### ISSUE TITLE
Anime Breakdown by ratings rather than watches

### ISSUE THREAD

**Issue by Shou** [hummingbird-me/hummingbird#359]
I feel like the anime breakdown is a mis-representative of the user considering the user might not have actually *enjoyed* watching many of the shows and rated them badly, as is the case with a lot of compulsive anime watchers. A user's taste also changes with time and as they readjust their ratings the anime breakdown just displays the total taste rather than current, more relevant taste. I propose instead to use the ratings the user gave to weigh in and the statistics be about what genre the user enjoyed watching the most. Assume a non-rating is neutral and therefore the same as the current system if a user rates nothing.

**Comment by JoshFabian** [comment]
This sounds agreeable enough, however it's not a trivial change. Feel free to open a pull-request if it's something you're capable of doing.

**Comment by NuckChorris** [comment]
The biggest problem I think is figuring out how to reasonably display such data: right now we show the numbers and users might get confused when bigger number =/= bigger slice

**Comment by erengy** [comment]
Speaking of which, another complaint would be that the graph tends to display generic genres on top. For instance, while I don't particularly enjoy watching comedy series, there are so many of them that it ended up being the second genre listed on my profile.

While I'm on it, Anime Breakdown should eventually link to a more detailed statistics page as in Hummingbird Tools, Hummingboard and MALgraph, though you probably have this in mind already.

**Comment by NuckChorris** [comment]
I'd do (number_watched + (0.5 * number_ptw)) * average_rating / number_of_shows_globally_with_that_genre, if the numbers weren't an issue

**Comment by cybrox** [comment]
Nuck's way of calculating makes sense, might be a bit confusing for users at first though. Also, we might need to add some special conditions for common genres since Comedy/Action would still always be \#1.

@erengy Yes, I definitely want to implement advanced stats, hence the reason why I originally created Hummingboard before I joined the team.

**Comment by NuckChorris** [comment]
The comedy/action would be down weighted by that final division.


The user confusion is the problem with any solution like that, though

**Comment by erengy** [comment]
Add a tooltip and/or display the results as percentage, perhaps?

**Comment by NuckChorris** [comment]
It's not really possible to do a sane percent ("why doesn't this add to 100!?") when there can be N genres on a given anime :/
