### ISSUE TITLE
receiving inactive account emails for previous usernames

### ISSUE THREAD

**Issue by DennisPacewicz** [hummingbird-me/hummingbird#379]
just wanted to mention that i'm receiving multiple emails from josh@hummingbird.mail.intercom.io about having an inactive account for multiple usernames (since i've changed my username a couple times), even though the current username on my account is in constant use. 
if possible, it would probably be best to link this email service to accounts rather than usernames.

**Comment by JoshFabian** [comment]
Hey Dennis,

Yikes! Sorry about that, the way intercom tracks definitely doesn't account for username changes, good catch. Will fix that in the future!
