### ISSUE TITLE
Refactor global instant search

### ISSUE THREAD

**Issue by cybrox** [hummingbird-me/hummingbird#385]
We have multiple components that implement the instant search in different form, that is `favorite-search`, that will filter after a certain list, `instant-search` for the header that implements the form focus/blur event and one in the search controller.

I did not want to take on refactoring all of these out when building the new favorite system, so I just created the favorite-search component but the instant search itself should definitely be refactored before it's used in other places (feed tagging for example)

Keeping favorite-search or instant-search (header-search) in a component per-se is not a problem, since this is the best way to go but we need to **break out the actual instant seach in a new parameterized component**.

Arguments include:
- Favorite endpoint (we need to add a search endpoint that works the same for all media types!)
- Entries limit (optionally page param for the api)
- The given search term

Component will trigger
- *listUpdate* event after Bloodhound fetched the new results with an array of data

**Comment by NuckChorris** [comment]
Also relevant is the search for waifu

**Comment by vikhyat** [comment]
@NuckChorris To what extend does #418 cover this?

**Comment by NuckChorris** [comment]
#418 doesn't cover this at all.  This is a complementary refactor on the frontend, to combine all the disparate search components we have
