### ISSUE TITLE
liking a timeline item stops any possible open YouTube videos on the timeline

### ISSUE THREAD

**Issue by dmitriyha** [hummingbird-me/hummingbird#405]
the timeline page seems to refresh when liking a timeline item, thus stopping any possible open YouTube videos on the timeline.

this issue was noticed on Win7 and the latest Firefox browser

**Comment by NuckChorris** [comment]
It re-renders the nodes which results in that reset.  I think this has hit all the best of us.

Also I just want to note that your identicon is an upside-down anchor.  Yo ho!

**Comment by dmitriyha** [comment]
regarding my identicon: that's what i got when signing up, and i love it :D

**Comment by vikhyat** [comment]
This will be probably be resolved once the reactive rendering PR lands in htmlbars.

**Comment by vevix** [comment]
Closing this as it's out of our control. Hopefully the future Ember rendering doesn't have this problem.
