### ISSUE TITLE
Sharing an anime with facebook

### ISSUE THREAD

**Issue by v4lproik** [hummingbird-me/hummingbird#505]
CSS div overlap issue when I try to share an anime with the FB like button.

![screen shot 2015-04-22 at 22 29 58](https://cloud.githubusercontent.com/assets/2066462/7284633/558a19fc-e93f-11e4-959f-4fe26ff63dcf.png)

Configuration : 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
Screen Resolution:	1920 px x 1080 px

**Comment by KustoSan** [comment]
.fb_iframe_widget iframe {
  max-width: none !important;
}

Would fix width:
![j775b7y](https://cloud.githubusercontent.com/assets/10654839/7356230/01120222-ed27-11e4-9adc-8583e78c73d4.jpg)

**Comment by NuckChorris** [comment]
Send a PR! :smile:
