### ISSUE TITLE
Padding issue from a timeline post

### ISSUE THREAD

**Issue by v4lproik** [hummingbird-me/hummingbird#506]
Is there a reason why the right padding value is set to 0 for li child ?

![screen shot 2015-04-23 at 12 32 11](https://cloud.githubusercontent.com/assets/2066462/7295328/04352b52-e9b5-11e4-9428-0b576fb86b77.png)

**Comment by vevix** [comment]
Another fix may be to add `padding-right: 15px` to the parent `ul` block.

**Comment by v4lproik** [comment]
Yes, you are right. The class follow-bubbles which holds the properties of the ul block comes from a third-party license file (). Where do you want to overload the ul property ?

The easiest solution would be to include at the beginning of the templates/user/index.hbs : 
`<style type="text/css">
    .follow-bubbles{
        padding-right: 15px;
    }
</style>`

Don't really like this solution though...
