### ISSUE TITLE
Implementation of a redirection link in an anime view

### ISSUE THREAD

**Issue by v4lproik** [hummingbird-me/hummingbird#507]
It might be good to create a link for each genre in an anime view.

Each link will redirect the user to :
https://hummingbird.me/anime/filter/all?utf8=%E2%9C%93&commit=Apply&g%5B%5D=name_of_the_genre

![screen shot 2015-04-23 at 18 24 28](https://cloud.githubusercontent.com/assets/2066462/7301992/7f4dff72-e9e6-11e4-91ef-b0e9dbd87e21.png)

For instance, if the user clicks on "action", the user is redirected to the anime search view with all the animes that are tagged with the action genre.

**Comment by vevix** [comment]
:+1: but this should be done after we have converted the filter page to Ember.

**Comment by v4lproik** [comment]
Cool ! Let me know if you need any help with this.
