### ISSUE TITLE
posterImageThumb returning non-existent Images

### ISSUE THREAD

**Issue by Kenshii** [hummingbird-me/hummingbird#512]
Medium and original sized images keep the original extension. Large is converted to jpg.
Most poster images work fine, because most were originally jpg in the first place.
posterImageThumb replaces /large/ with /medium/, though, so .png's would return 404, for instance.

https://static.hummingbird.me/anime/poster_images/000/003/936/large/gqt6iYB.jpg - JPEG
https://static.hummingbird.me/anime/poster_images/000/003/936/medium/gqt6iYB.png - PNG
https://static.hummingbird.me/anime/poster_images/000/003/936/medium/gqt6iYB.jpg - Non-existent

posterImageThumb is used by the favorites editor.
It's defined in /frontend/app/models/anime.js

**Comment by vevix** [comment]
Hmm, we only use the medium style on the old explore page so we don't currently serialize the url into Ember.

If we serialize it then we'll probably have to update the "fastpath" method we use for URL generation.

**Comment by Kenshii** [comment]
It's used for favourite anime ranking:

![image](https://cloud.githubusercontent.com/assets/290316/7379666/6376584c-edee-11e4-8098-7c8937f6bc6b.png)

**Comment by Kenshii** [comment]
The bug in action:
![image](https://cloud.githubusercontent.com/assets/290316/7379711/b105c8d6-edee-11e4-983e-f790b3773576.png)

**Comment by DNA** [comment]
Fixed on #586. We can close this issue now :)
