### ISSUE TITLE
API method to post an update to the User's Timeline

### ISSUE THREAD

**Issue by chikorita157** [hummingbird-me/hummingbird#518]
Is there any plans to add a API function in API Version 2 to make it possible to post an update to the user's timeline? I want to add a function to my application that allows the user to post an update for the show they have watch... probably something like this:

POST /users/feed
id: (optional, can be a slug or id)
episode: (optional)
message: (required)

**Comment by vevix** [comment]
API v2 is going to be done via OAuth so we'll probably allow you to post to users feeds, assuming they give you permission.

It'll be text only posts tho, We already create media updates automatically when you update their library.

**Comment by NuckChorris** [comment]
Adding to what thomas said, the APIv2 stuff will be properly RESTful, which means you'll create a whole Post object and upload it, not just fill in a couple parameters to a "make a feed post" endpoint
