### ISSUE TITLE
genre filter "all" checkbox

### ISSUE THREAD

**Issue by sachaw** [hummingbird-me/hummingbird#521]
just thought that the "all" button under the filter by genre box should be automatically unchecked when the list is altered and they are no longer all checked, the same goes for once everything is checked automatically check it.
![genre list](https://cloud.githubusercontent.com/assets/11172820/7427091/0f2c4a04-f013-11e4-9833-208638b022a4.PNG)
also, could the overflow of "anime influenced" be fixed.

**Comment by NuckChorris** [comment]
That's one of our old-design pages.  We're not going to bother with minor bugfixes for it, only fixes for major regressions like "it stopped working entirely."

We're working on an entirely new version, I believe @cybrox is coming along quite nicely with that (?)

**Comment by sachaw** [comment]
K thanks nuck
