### ISSUE TITLE
Wrong informations in the anime franchies overview

### ISSUE THREAD

**Issue by simonknittel** [hummingbird-me/hummingbird#525]
At the bottom of the anime details page you have the franchise overview.

The informations (airing date, episode count, etc.) of these anime are always the information of the anime which page you are on.

![4_5_2015_20_47_5](https://cloud.githubusercontent.com/assets/8451099/7459824/f3b4394c-f29e-11e4-8159-2f94b1585714.jpg)

**Comment by NuckChorris** [comment]
ahahaha nice catch wow how did I not notice that before
