### ISSUE TITLE
Manga and Anime genres all messed up.

### ISSUE THREAD

**Issue by sachaw** [hummingbird-me/hummingbird#529]
I just looked at the Tokyo ghoul manga page https://hummingbird.me/manga/tokyo-kushu
And realized that all the genres were not spaces, don't know if this just for me or this has already been reported.
![image](https://cloud.githubusercontent.com/assets/11172820/7465684/fd560e4c-f313-11e4-8bb8-d9f3e54ee6dc.jpg)

**Comment by vevix** [comment]
@wopian I think this might be because of your removal of the padding-right in the recent PR?

**Comment by vevix** [comment]
This should remain open.

**Comment by wopian** [comment]
>@wopian I think this might be because of your removal of the padding-right in the recent PR?

Yeah guess I never thought of checking anime/manga pages ;_;

Dunno why it's all lowercase though?

**Comment by vevix** [comment]
For lowercase issue:

https://github.com/hummingbird-me/hummingbird/blob/0423a53d95eefd4b4a1b9edd156515acc4485751/app/serializers/manga_serializer.rb#L22

should be changed to:

`object.genres.map(&:name).sort`

**Comment by wopian** [comment]
This can now be closed.

**Comment by vevix** [comment]
I'll leave it open until the padding is fixed

**Comment by wopian** [comment]
:facepunch: mixed it up with the lowercase genres :confounded:

**Comment by sachaw** [comment]
soz for close, when I saw 0423a53d95eefd4b4a1b9edd156515acc4485751 i though it was fixed, but diddnt check

**Comment by wopian** [comment]
>soz for close, when I saw 0423a53 i though it was fixed

That was fixing this and a few other things:

![](https://camo.githubusercontent.com/380fc2ddcc51b25ccfd2c71619e047c783e57e9e/687474703a2f2f612e706f6d662e73652f6d696277786c2e706e67)

**Comment by sachaw** [comment]
Yea, I realised, just a bit 2 late.
