### ISSUE TITLE
Expose TVDB IDs in API

### ISSUE THREAD

**Issue by matthewdias** [hummingbird-me/hummingbird#547]
It's probably tricky to match these since hummingbird treats seasons as separate shows, but if we could get most of them to stick and leave the rest up to user input it would enable some pretty cool possibilities:

- Prompting to watch next season of a show on completion
- Richer franchise data
- Compatibility with pretty much any software that deals with tv/movie management
- Air times
- *** less reliance on MAL ***

**Comment by wopian** [comment]
I believe we already have the IDs of all the anime linked.

**Comment by NuckChorris** [comment]
We have this data in the DB, but it turns out TVDB is basically worthless for anime

**Comment by matthewdias** [comment]
oh damn, do you think we could get this in api v2 tho?

**Comment by NuckChorris** [comment]
I guess we could expose them similar to how we expose MAL, with `tvdb:seasonid` for an ID and including it in the output. Lots of shows don't have it tho

**Comment by NuckChorris** [comment]
Er, by don't have it I mean don't exist in TVDB

**Comment by NexPB** [comment]
@NuckChorris What do you mean it's worthless for anime? I'm using it for my site and it's really useful for hummingbird's episode feature.

**Comment by wopian** [comment]
@NexPB 

>Lots of [anime] shows don't exist in TVDB

**Comment by wopian** [comment]
@NexPB 

>Lots of [anime] shows don't exist in TVDB

**Comment by wopian** [comment]
@NexPB 

>Lots of [anime] shows don't exist in TVDB

**Comment by NuckChorris** [comment]
Renaming this to better match the conclusion of current discussion.

We already have TVDB info but need to expose it in the API.  This is a pretty easy addition in APIv2, where we already expose MAL IDs via `myanimelist:1234` as the ID.

Some discussion will be required as to whether we should expose the `tvdb_season_id` or `tvdb_series_id`.  One option is to expose both, returning a _list_ of shows that match a given `tvdb_series_id` or returning a single show with a specific `tvdb_season_id`
