### ISSUE TITLE
Studios not correct aligned when they enter a third line

### ISSUE THREAD

**Issue by Eschon** [hummingbird-me/hummingbird#548]
![unbenannt](https://cloud.githubusercontent.com/assets/11647830/7628161/058b5dca-fa20-11e4-96ab-99f5d2613760.PNG)

As seen in the screenshot the alignment breaks when entering the third line. This would probably also be the case for genres but I have found no anime where this is the case.

**Comment by astraldragon** [comment]
One way to fix it is to add padding to the .inline-list class in each respective list (genres, studios).  I tried padding-left: 58px; and everything seemed to line up.

**Comment by Eschon** [comment]
@astraldragon do you plan on submitting a PR for that? Otherwise I'll do it.

**Comment by Eschon** [comment]
Just found an example where this also happens on genres

![selection_001](https://cloud.githubusercontent.com/assets/11647830/7794923/205f1a66-02d0-11e5-9b5f-829b64e60353.png)

It's also fixed with the fix suggested by @astraldragon

**Comment by astraldragon** [comment]
I can submit a PR for it later today

**Comment by Eschon** [comment]
Ok thanks

**Comment by wopian** [comment]
>@astraldragon  I tried padding-left: 58px; and everything seemed to line up.

If you're going to do that use `padding-left: 54px;` so it doesn't change the spacing. 

Using this method also breaks the layout on smaller window sizes as the **Genre** & **Studios** become their own lines - so you'll need to wrap this in a `@media` query so lower widths remain unchanged.

![](http://i.imgur.com/deSReat.png)
Genres: With `padding-left 54px` (or 58px)
Studios: Original intended layout

**Comment by astraldragon** [comment]
@wopian Would you rather have both lists start on the new line on all screen sizes?  Or do you like the padding applied only on the normal layout?

**Comment by wopian** [comment]
Padding applied to normal layout only - to conform with the current design.
