### ISSUE TITLE
Broken waifu/character URL's

### ISSUE THREAD

**Issue by sachaw** [hummingbird-me/hummingbird#554]
I have come across this in the past, but upon changing my waifu (plz don't hate) to Kumiko Oumae from hibike euphonium I noticed that the URL's is broken: https://hummingbird.me/anime/hibike-euphonium-kitauji-koukou-susougaku-bu-e-youkoso so I'd thoud id open up this issue for anyone with broken URL's, plz correct me if this not the right place to post.

**Comment by NuckChorris** [comment]
Known issue, will be solved in #375
