### ISSUE TITLE
Remove black lines from side of avatars

### ISSUE THREAD

**Issue by sachaw** [hummingbird-me/hummingbird#568]
Upon looking at my avatar recently, I realized that there were thin black lines on either side of the transparent image, I just thing that it would look better without these.
![image](https://cloud.githubusercontent.com/assets/11172820/7953250/bc1f62fc-0a01-11e5-876f-ddb8dc723cad.jpg)

**Comment by wopian** [comment]
The image you used was most likely not perfectly square, so when its been uploaded black bars were added to the edges to make it square.

**Comment by DNA** [comment]
Can you send us the original image you uploaded, so we can check it?

**Comment by sachaw** [comment]
Yea, the origins
 Image was not square, so I'll just crop and reupload it and see what happened,also what is the size of the image?

**Comment by NuckChorris** [comment]
The image will be scaled to many sizes, just upload the biggest square image you've got



—Peter

**Comment by NuckChorris** [comment]
Also leaving this open since we should fix the cropping code to not add black sections



—Peter

**Comment by sachaw** [comment]
ok, thx 4 the help.

**Comment by sachaw** [comment]
UPDATE: I corrected the shape of my image (300 * 300) and the lines were fainter but still apparent 
![capture](https://cloud.githubusercontent.com/assets/11172820/7974582/76da3252-0aa2-11e5-888d-55829daa7c40.PNG)

**Comment by AinaM** [comment]
The lines come from a slight shadow behind the avatar, it's on each profile :)
The image is transparent so the result is a little bit strange... Perhaps it would be better with a very transparent white behind the avatar ? 
Like this : 
![screen_avatar](https://cloud.githubusercontent.com/assets/5560784/7981802/b77e8876-0ab1-11e5-9646-4397c7f58aa4.png)

**Comment by TillaTheHun0** [comment]
+1 for @AinaM's suggestion

**Comment by JoshFabian** [comment]
+1 for @AinaM's suggestion as well. Pull request?

**Comment by NuckChorris** [comment]
Why do we even put a shadow there? :/

**Comment by JoshFabian** [comment]
So that avatar's don't get lost in the cover photo, of which can be myriad colors.

**Comment by NuckChorris** [comment]
But what if a user wants to blend it into the image on purpose? :stuck_out_tongue_winking_eye:

**Comment by sachaw** [comment]
I think it would be better if there was an option or if it could detect weather certain edges of the image are transparent and only apply the shadow to sides that are not transparent, then the image would not get lost and there would be no lines.

**Comment by NuckChorris** [comment]
We can't do that, the shadow is CSS

**Comment by sachaw** [comment]
dam, well then why don't we have a checkbox under the profile cover editor labeled "apply shadow" or something?

**Comment by NuckChorris** [comment]
Because options are the devil

**Comment by sachaw** [comment]
yea

**Comment by sachaw** [comment]
a dodgy 1 min job and this'll prob not happen but i was thinking like this 
![capture](https://cloud.githubusercontent.com/assets/11172820/7998818/d8bf0176-0b80-11e5-87b5-d34d0111731d.PNG)

**Comment by DNA** [comment]
+1 for @AinaM's suggestion as well. It'll look nice even when you don't want to mix your avatar with the background, and can works as well when you can merge it.  

Did we got some definition about this? :P

**Comment by NuckChorris** [comment]
:+1: would merge, @AinaM feel like sending a PR with that? It's probably somewhere in `app/assets/stylesheets`

**Comment by sachaw** [comment]
it would be good but again, if the user wants to merge it with there cover
