### ISSUE TITLE
Profile image thumb returning Forbidden (403)

### ISSUE THREAD

**Issue by TillaTheHun0** [hummingbird-me/hummingbird#571]
The profile image thumbnail is receiving a 403 and therefore does not appear while logged in. In Chrome 43.0.2357.81 on OSX 10.10.3:

![screen shot 2015-06-05 at 8 28 24 am](https://cloud.githubusercontent.com/assets/8246360/8005928/0675b976-0b5d-11e5-9f76-f39dfee21a84.png)

![screen shot 2015-06-04 at 1 49 19 pm](https://cloud.githubusercontent.com/assets/8246360/8005866/8f29e2ca-0b5c-11e5-8719-bc0f3748cfea.png)

**Comment by wopian** [comment]
The smaller images URLs are `https://static.hummingbird.me/users/avatars/000/069/146/thumb_small/open-uri20141130-13881-ju495t?1417316294` - no file extension oddly.

Have you tried re-uploading the avatar?

**Comment by TillaTheHun0** [comment]
Got it. It wouldn't let me change it at first. I had my account connected to Facebook a long time ago and It still had an old profile picture on hummingbird from there. I had to disconnect Facebook, sign out-in and then It would let me change it. All is well!
