### ISSUE TITLE
Anime genres are duplicated on Dashboard and User pages.

### ISSUE THREAD

**Issue by wopian** [hummingbird-me/hummingbird#575]
![](http://i.imgur.com/b4gKy3u.png)

Although it seems *sometimes* it'll only show it once (maybe its because it only has 1 genre?)

![](http://a.pomf.se/snebqe.png)

Reported in this story: https://hummingbird.me/stories/5477299

**Comment by vevix** [comment]
Seems to be caused by the addition of the `default_scope` on the anime model.

**Comment by NuckChorris** [comment]
Oh god you're probably right. The story controller tries to do some funky shit with autoloading

**Comment by DNA** [comment]
Well, at least the scope fix are already done on #577, we just need to send it to production :P 

(I laughed at "funky shit with autoloading" xD)

**Comment by NuckChorris** [comment]
Sadly that scope fix probably won't fix this.  This is because we preload the genres in that scope (good!) but the `SearchQuery` forcibly preloads things via some strange hacks.  We probably need to `.unscoped` it

**Comment by DNA** [comment]
~some strange hacks~ issue resolved xD

**Comment by wopian** [comment]
Fixed.
