### ISSUE TITLE
OAuth2 Rollout and APIv1 Login Deprecation Discussion

### ISSUE THREAD

**Issue by NuckChorris** [hummingbird-me/hummingbird#587]
(cc @Mikunj @fractalemagic @erengy @inket @z411 and any other third-party devs)

With #583 fast approaching (about 8 hours of work remain before we can start doing QA), I'd like to open a discussion regarding rollout plans for OAuth2 and deprecation plans for the APIv1 login system.

OAuth2 will provide a near-drop-in replacement for the APIv1 login in the form of the [Resource Owner Password](http://tools.ietf.org/html/rfc6749#section-4.3) grant alongside the `all` or `apiv1` scopes.  The only real difference is in the response schema and the requirement of staff review for access to features such as the password grant and the `all` scope — though honestly, we'll be rubberstamping almost all current clients.

What makes OAuth2 interesting is that we can actually make it more secure with time.  APIv1's login was a security dead end.  With OAuth2, we can incessantly nag our beloved third-party developers to reduce their scopes and switch from the password grant to other grant types, and in the process gain the trust of more security-minded users.  Plus us staff will not be so terrified of using your apps.

To this end, I'm recommending the following rollout/deprecation schedule, and would like to hear feedback from the rest of the team, our contributors, and all our app developers.  Users who refuse to update?  OAuth2 killed your waifu?  Please tell me so we can work out a solution.

First we'll push a beta.  During beta, we'll work alongside third-party developers to work out any kinks.

* Beta (Day -1)
   * Announcement post in dev/api along with explanation, links to libraries and OAuth Bible
   * New tokens issued by APIv1 are tagged as such so we can handle them separately

After things look stable for a week or so, we'll call it final and move to Gold Master.

* Gold Master (Day 0)
   * APIv1 login deprecated (not removed!) in favor of OAuth2 with `apiv1` or `all` scope and `password` grant
* Gold Master (4 Months Later)
   * Tokens issued by APIv1 (identified by above tagging) are no longer accepted by the rest of the site or on the forums
* Gold Master (8 Months Later)
   * Look for any remaining clients using APIv1 login, email the developers.  Unauthenticated APIv1 applications will continue working as usual.
* Gold Master (1 Year Later)
   * APIv1 login is removed entirely
* <strike>Gold Master (10 Years Later Ver.)</strike>
   * <strike>We meet at the Secret Base and ghost and a reunion happens</strike>
   * <strike>Cry like a bitch because AnoHana</strike>

I want to make sure we have Taiga, Trackma, Deadman, Tenpenchii, Anitro, and HAPU onboard for this process.  I know it sounds crazy, and the Pull Request implementing it is _fucking insane_, but it's really quite simple from the perspective of an app developer.

**Comment by inket** [comment]
Sounds good. :shipit:

**Comment by DNA** [comment]
As we are talking about APIs and gathering dev users, I think that it's important to consider the API V2 in this as well. How would be the best approach to tackle both the oauth and api version change?

I'm asking this because I'm thinking in focusing on the APIV2 from now on, but I need to know the needs and concerns you guys have about that. I'll do a follow up of this so we can have a good API shift withouth any headaches :)

**Comment by NuckChorris** [comment]
Luckily the switch to APIv2 is separate from the switch to OAuth2, so we don't really have to worry about that.

We can do this today and slowly shuffle things onto APIv2 over the next year or so. Eventually we can deprecate APIv1 as well but that will be a much slower phase-out and it won't be until APIv2 reaches parity

**Comment by z411** [comment]
Trackma already supports PIN-based, token-based OAuth authentication so as long as it follows standard procedure we shouldn't have any major issues. Thanks for the heads up.

**Comment by erengy** [comment]
Same here. Taiga already uses OAuth for Twitter, though I imagine the authorization process might be different for Hummingbird. In any case, I'll find a way to make it work as soon as possible.

**Comment by NuckChorris** [comment]
Twitter uses OAuth1, not OAuth2.  Sadly, the two are really just related in name.  OAuth2 is simpler though, so if you managed to implement OAuth1, you can easily implement OAuth2.

**Comment by Mikunj** [comment]
Shiet i'm like 1 month late on this ...
err what's the progress atm?
Going to start working on deadman this week

**Comment by NuckChorris** [comment]
Mostly just waiting on me to set it up on my server and throw as many libraries as I can at it

**Comment by infrequent** [comment]
Got a unused DO box atm if you need extra resources for nothing mission critical; lots of down time for AT projects atm
