### ISSUE TITLE
Romanized title language preference

### ISSUE THREAD

**Issue by erengy** [hummingbird-me/hummingbird#599]
Setting the `title_language_preference` parameter to `romanized` in APIv1 no longer has any effect.

The following request is supposed to return the romaji title as `title` and the English one as the `alternate_title`, but it prefers the canonical one instead:
http://hummingbird.me/api/v1/anime/7169?title_language_preference=romanized

Here's what APIv2 says about the same anime:

```json
"id": 7169,
"titles": {
  "canonical": "My Teen Romantic Comedy SNAFU",
  "english": "My Teen Romantic Comedy SNAFU",
  "romaji": "Yahari Ore no Seishun Love Comedy wa Machigatteiru.",
  "japanese": "やはり俺の青春ラブコメはまちがっている。"
}
```

@DNA I think this worked correctly up until d72d84ee194cbfd04f9ae2fa59d0d2471fbcca5e, which apparently erased comparison with "romanized" in `canonical_title` and `alternate_title` functions.

**Comment by DNA** [comment]
I'll look into it this week, and add more tests to prevent it to happen again :)

**Comment by DNA** [comment]
Corrected code done! Now we just need to bug @NuckChorris to approve it :P
