### ISSUE TITLE
Importer should use higher resolution posters

### ISSUE THREAD

**Issue by synthtech** [hummingbird-me/hummingbird#608]
Somewhat similar to what I mentioned [here](https://forums.hummingbird.me/t/character-images-all-blurry/25712/2?u=synthtech), except for anime and manga posters.

Something that appends "l" to the filename will allow the importer to grab a (usually) better quality version of a poster.

Ex.

Thumbnail | Full-size
--- | ---
http://cdn.myanimelist.net/images/manga/2/161562.jpg | http://cdn.myanimelist.net/images/manga/2/161562l.jpg
![](http://cdn.myanimelist.net/images/manga/2/161562.jpg) | ![](http://cdn.myanimelist.net/images/manga/2/161562l.jpg)

**Comment by sachaw** [comment]
this would look great!

**Comment by NuckChorris** [comment]
This is probably a super simple change in the MAL importer.  If somebody wants to do this, look in `lib/mal_import.rb` — it might be as simple as changing a `gsub` in some cases

**Comment by DNA** [comment]
I'm pretty sure it's on https://github.com/hummingbird-me/hummingbird/blob/master/lib/mal_import.rb#L158
Just changing `img.gsub("v.jpg", ".jpg")` to `img.gsub("v.jpg", "l.jpg")` should do the trick, but I'm lacking time to test this :P

**Comment by NuckChorris** [comment]
That should be at least part of it.  There are other places we handle images where I think we forget to remove `v.jpg` (images of VAs or characters)
