### ISSUE TITLE
Time spent on anime computation

### ISSUE THREAD

**Issue by vevix** [hummingbird-me/hummingbird#620]
We recompute the time spent on anime in a `before_save` hook on `LibraryEntry` which will always be zero for the first library entry.

```ruby
  def update_life_spent_on_anime(delta)
    if life_spent_on_anime == 0
      self.recompute_life_spent_on_anime!
    else
      self.update_column :life_spent_on_anime, self.life_spent_on_anime + delta
    end
  end
```
https://github.com/hummingbird-me/hummingbird/blob/068c195dc53d482fb2a22b2db3163e201dca0022/app/models/user.rb#L371-L390

**Comment by pixeldesu** [comment]
_Sort of another issue, but it fits:_ Wouldn't it make more sense to compute time for anime with the amount of episodes watched no matter what status the `LibraryEntry` has (ex.: someone watched a 600 episode anime half and dropped it, but the time never gets measured)? I heard a lot of people complaining about that after I've shown them HB.

**Comment by vevix** [comment]
That's exactly what we do. Whenever `episodes_watched`, or 'rewatching' changes we recompute the time.

**Comment by NuckChorris** [comment]
Can we just change it to an `after_save` hook to fix it for now

**Comment by DNA** [comment]
If the formula to calculate it is right, I'm okay with just changing the hook

**Comment by vevix** [comment]
Will probably require some more changing than that, pretty sure it relies heavily on `_changed?` checks.
