### ISSUE TITLE
500 Error when middle clicking anime link from library

### ISSUE THREAD

**Issue by hypereddie** [hummingbird-me/hummingbird#622]
I seem to get a 500 error when I middle click an anime link in my library (try to open the link in a new tab). The link works fine if I just normally click it, but I'd really like to be able to open a bunch of them in separate tabs

# How to reproduce
1. Go to your library
2. Right click an anime link
3. Click "Open link in new tab"
4. See 500 error

# Video
[Here's a video of me reproducing the error](https://drive.google.com/file/d/0BxW8HsiobN-KZGdPUjloNEpJLU0/view?usp=sharing)

**Comment by NuckChorris** [comment]
Fixed and deployed
