### ISSUE TITLE
Inconsistent Headers

### ISSUE THREAD

**Issue by rushsteve1** [hummingbird-me/hummingbird#624]
There has been a long-standing issue that the header and its sub-menus are not the same across all pages. The colors, menu listings, and action that opens the menu, are all different from the ones on the Dashboard page, which is the most up to date.

Example:
The menu in the Dashboard:
![image](https://cloud.githubusercontent.com/assets/5970439/9253262/effcf7ac-41aa-11e5-9306-a27b018c57a2.png)

The menu on the explore page:
![image](https://cloud.githubusercontent.com/assets/5970439/9253344/53eb1c62-41ab-11e5-89ab-aefea786a335.png)

This is a large navigation issue, as it is currently impossible to get to certain pages (ie: the manga library) without first going back to the Dashboard page.

The pages with the outdated header are:
* Recommendations
* What's Trending (anime)
* Explore (anime/filter/*)
* Upcoming (anime/filter/upcoming)

**Comment by NuckChorris** [comment]
I'd swear there was already an issue for this, but it's basically a result of us slowly redesigning old pages.  The explore/filter page already has a new design that just needs implementing, and the others are waiting on similar work.

If you want to send a PR changing the links, it's over in `app/views/shared/_header.html.haml`
