### ISSUE TITLE
Titles are rated before airing of the 1st episode

### ISSUE THREAD

**Issue by tenno-seremel** [hummingbird-me/hummingbird#632]
$SUBJ happens, and I think it shouldn't.

**Comment by pixeldesu** [comment]
:+1:

I've seen this happening a lot (even on other sites) and I think pre-air ratings should be disabled.

**Comment by NuckChorris** [comment]
I wonder if it would be possible to do a separate "hype rating" amongst users who haven't started watching yet.  At the very least, I can agree with not showing the average rating if it hasn't started airing yet.

But I'll be damned if I let anybody stop me from rating shows before they air.

**Comment by vevix** [comment]
>I can agree with not showing the average rating if it hasn't started airing yet.

I'm pretty sure we already do this.

**Comment by Eschon** [comment]
I think shows being rated before they air is a nice way of seeing what people look forward to. I don't think it should be disabled.

**Comment by tenno-seremel** [comment]
> I think shows being rated before they air is a nice way of seeing what people look forward to. I don't think it should be disabled.

Shouldn't “plan to watch” do that?

**Comment by JoshFabian** [comment]
I think I agree with not being able to rate a show before it has aired. Plan to watch indeed acts as an indicator of interest.

**Comment by Eschon** [comment]
>Shouldn't “plan to watch” do that?

When someone puts 20 shows on "plan to watch" I know that  he probably will watch those 20 shows but I don't know how much he is looking forward to them.

**Comment by JoshFabian** [comment]
@Eschon If we were to gauge interest by measuring site-wide plan to watch activity, we could probably establish a reasonable 'trending' list for an upcoming season. I think the only other alternative is resetting ratings on the day the show aires.

**Comment by NuckChorris** [comment]
I use ratings on my PTW list to sort them.  Until we have a reasonable sort mechanism, I don't want to remove preratings.  I think we should just treat preratings separately from postratings

**Comment by JoshFabian** [comment]
Planning a proper ordering mechanism for PTW is probably smart. Separate
pre and post ratings has a lot of potential to be confusing to users, as
well as cluttering the UI to allow users to adjust / change / remove / show
their prerating after a show has aired.

**Comment by NuckChorris** [comment]
Nah I meant just treat ratings on the PTW differently from ratings on the completed lists.  Then you display two separate averages
