### ISSUE TITLE
User feed filter background color

### ISSUE THREAD

**Issue by sachaw** [hummingbird-me/hummingbird#642]
Looking that the user feed filter, it seems to get a little lost and doesn't have a very compliant design, I thought doing something like this:
![improved](https://cloud.githubusercontent.com/assets/11172820/9837226/72f5e738-5a77-11e5-82e5-11321b056ef2.PNG)
As against the original:
![original](https://cloud.githubusercontent.com/assets/11172820/9837228/7c46c1c2-5a77-11e5-98e3-a285cda3ef1e.PNG)
It could do with some text color changes or even a font change but I believe something needs to be done.

**Comment by wopian** [comment]
Something like this? cc @JoshFabian 

After:
![](https://i.imgur.com/BNdvvHQ.png?1)

Before:
![](https://i.imgur.com/HQv06Be.png?1)

**Comment by sachaw** [comment]
yea, looks good
