### ISSUE TITLE
 Adding CORS to apiv1

### ISSUE THREAD

**Issue by Kcchouette** [hummingbird-me/hummingbird#644]
Seems to be similar to #297 (but this PR has been rejected) and https://forums.hummingbird.me/t/cors-access-to-main-site-api/16862

Is there a way to add CORS to apiv1 for javascript call support?

Thanks

**Comment by Kcchouette** [comment]
To enable it, juste add `Access-Control-Allow-Origin: *` to the response header.

**Comment by DNA** [comment]
I can't remember any security implication as said in the other PR, I don't see any problem with it, but it's better to see if @NuckChorris can remember some obscure problem related :laughing:

**Comment by Kcchouette** [comment]
Please don't forget that to the next version! Thanks :wink:
