### ISSUE TITLE
Don't overwrite existing anime data when importing

### ISSUE THREAD

**Issue by synthtech** [hummingbird-me/hummingbird#647]
I've suspected for a while now that something is enabling the importer to overwrite certain data such as the media type, age rating, episode count, episode length, started and finished air dates. I've made the assumption that an entry import is triggered when someone imports their list, but I'm really not too sure what the actual behaviour is.

Example:
![](https://puu.sh/kjxhC/75533e5a72.png)
(I had accepted an edit a few days ago that had the correct episode count and length, and it's quite obvious that the importer must have reverted it since then)

It's become more of a major issue recently since the broken importer in combination with this is automatically overwriting seemingly random entries in the db:
![](https://puu.sh/kjBI4/11d7b8ef56.png)

Also, it's possible this may also apply to manga as well, I just haven't noticed anything so far.

**Comment by vevix** [comment]
We only run the importer when we find an anime, or manga in a list that isn't already in our database.

The only other way is via the admin panel, which would overwrite data.

**Comment by synthtech** [comment]
Really? Then that would mean someone is forcing an import and not fixing up the info afterwards, since I've seen this happen many times on entries that are already in the db. :confused:

**Comment by wopian** [comment]
It's been reverted to ? many, many times since I first added all the data for this entry.

**Comment by vevix** [comment]
Is there a reason why community admins import from there? They get their
page edits automatically applied instantly. @NuckChorris can probably check
the logs to see if it's being abused.

**Comment by synthtech** [comment]
It could be used to try to update the castings/characters, but it usually doesn't work very well.
