### ISSUE TITLE
Unresolved issues closed

### ISSUE THREAD

**Issue by sachaw** [hummingbird-me/hummingbird#651]
Maybe i missed something, but all the previously open issues are closed, many of which are still apparent.

**Comment by pixeldesu** [comment]
Probably has to do with the current rewrite of Hummingbird which is happening in the the-future branch in this repository.

Most of the mentioned issues have been discussed and I'm sure they will take these in account and improve them right on the way.

**Comment by sachaw** [comment]
cheers, wasn't sure if i missed something major.

**Comment by JoshFabian** [comment]
Yep, exactly as Pixeldesu said.

**Comment by sachaw** [comment]
cool, cant wait
