### ISSUE TITLE
Discourse SSO

### ISSUE THREAD

**Issue by vevix** [hummingbird-me/hummingbird#653]
Implement official discourse SSO on a fresh discourse install. This should lead to a much more stable discourse instance than the one we're currently using.

https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045
# Goals

Line demarcates "initial release", everything after the line is stretch goals
## V2
- [x] Login (basic SSO)
- [x] Sync avatar

---
- [x] Sync `pro_expires_at`
- [x] Display PRO badge on forums
- [ ] Sync cover image
- [ ] Sync profile info (location, website, etc.)
## V3
- [ ] Login (basic SSO)
- [ ] Sync avatar
- [ ] Sync `pro_expires_at`
- [ ] Sync cover image
- [ ] Sync profile info (location, website, etc.)
- [ ] Sync permissions with SSO `moderator` and `admin`
- [ ] Sync bans to forums

---
- [ ] Logout when main site logs out
- [ ] Sync ignoring/blocking w/ Discourse "muted users" 
- [ ] Display Discourse notifications amongst main site notifications

**Comment by NuckChorris** [comment]
Added a checklist as I start working on this for V2.  V2 is gonna be smooth sailing for this, and the new plugin outlets system in Discourse provides us with easier ways to wedge our own stuff into the interface than our current overrides.  Will update when I have a branch on here for the integration and on [hummingbird-me/discourse-hummingbird](https://github.com/hummingbird-me/discourse-hummingbird) for any plugin features we need.  I don't think we'll need much.
