### ISSUE TITLE
Setup Docker

### ISSUE THREAD

**Issue by vevix** [hummingbird-me/hummingbird#654]
Create Dockerfile's for development purposes.

**Comment by NuckChorris** [comment]
# Install Instructions
## Client (Ember)
1. Install Node 0.12+ or io.js
2. Install Bower (`npm install -g bower`)
3. `cd client`
4. `bower install && npm install`

## Server (Rails)
1. Install Ruby 2.2.1, Postgres 9.3+, and Redis
2. Install Bundler (`gem install bundler`)
3. `cd server`
4. `bundle install`

# Running It
1. Install Foreman (`gem install foreman`)
2. Run `foreman start` at project root
