### ISSUE TITLE
User Blocking/Ignoring

### ISSUE THREAD

**Issue by vevix** [hummingbird-me/hummingbird#655]
Users should be able to block other users.

This should primarily stop the blocked party from posting on the users profile.

**Comment by NuckChorris** [comment]
How do we want to do this, from a user's standpoint? Ignore or block, or both?

**Comment by cybrox** [comment]
What would be the difference in this case?
I can imagine you could probably use ignore to just disable notifications when the user takes certain actions but I doubt most people would care about this at all. In fact, from what I can say from all the previous requests in the forums or HB in general, people wanted to just plain out block each other, in the sense of keeping each other from posting to their feed.

Alternatively, it might be worth considering adding a rickroll popup for the block button to spread some happiness before asking people if they really want to block each other.

**Comment by NuckChorris** [comment]
Benefit of ignore is that the ignored user cannot ever know they were ignored, preventing efficient sockpuppeting.

With a block we make it incredibly clear that the user isn't allowed to do that.

As for the usual "how do Twitter/Facebook/Grindr do this?"…

Twitter: offers separate block and ignore functionality, and advises you to report a user when you block them.
Facebook: I think just has defriending?
Grindr: literally just dongs

**Comment by NuckChorris** [comment]
Another thought occurs: what about this setup, in kind-of-cucumber form:

>Given that Sue blocks Joe
>When Joe attempts to post on Sue's profile
>Then Joe should see his post
>And Sue should not see his post
>And Sam should not see his post

Basically, similar to ninja banning, only users blocked by Sue would see posts by users blocked by Sue

**Comment by cybrox** [comment]
I agree that shadow-blocking might be the most valuable option here. Though I don't really see the change in concept of 
> users blocked by Sue would see posts by users blocked by Sue
Why not display the post only to the poster? I think it would cause a lot of confusion when some people can see the post while others are wondering why they don't.

**Comment by NuckChorris** [comment]
That's also viable. I think it moves ignoring up in usefulness and allows a smoother bridge to reporting, all the while reducing Options™. Since @josh gets all the complaint emails he might be able to say better
