### ISSUE TITLE
Username Tracking

### ISSUE THREAD

**Issue by JoshFabian** [hummingbird-me/hummingbird#674]
Store previous aliases of users, so that others aren't left in the dark when a user they're following changes their username.

**Comment by NuckChorris** [comment]
Tracking this is actually ultra-easy.  Do we want to store a limited number or &infin;?

**Comment by JoshFabian** [comment]
I think past 10 would be sufficient.

**Comment by NuckChorris** [comment]
Sure.  I might see about adding this during the QA period for V3.  It's such a small and simple feature

**Comment by NuckChorris** [comment]
Done in c2bdaad
