### ISSUE TITLE
APIv2 bulk request only gives episodes and gallery images of the last mentioned anime

### ISSUE THREAD

**Issue by exitium** [hummingbird-me/hummingbird#678]
For example, an HTTP request to "https://hummingbird.me/api/v2/anime/1,3,2" will return the episodes and gallery images of anime '2' only. http://pastebin.com/FrWTWiYx

**Comment by NuckChorris** [comment]
Patches welcome, otherwise this will probably wait to be fixed in a few months when `the-future` goes live, since we're focusing our efforts there

**Comment by NuckChorris** [comment]
This is already fixed in `the-future` :dancer:
