### ISSUE TITLE
Irregular length episodes within seasons

### ISSUE THREAD

**Issue by sachaw** [hummingbird-me/hummingbird#679]
just wondering how hummingbird handles these, for example the episode of kekkai sensen that just aired was 45 minutes and the rest of the season was a standard 24 minutes per episode, just wondering it those extra minutes are recorded or not?

**Comment by vevix** [comment]
We don't handle it on a per-episode basis. So in this case it would be recorded as 24m.

**Comment by NuckChorris** [comment]
Often what what uses the average episode length

**Comment by sachaw** [comment]
just seems kind of inaccurate, maybe you could have something like "12 episodes 24 min each + 45 min episode".

**Comment by NuckChorris** [comment]
Ideally we would be able to set per episode lengths, but right now that's not viable. Down the road it's possible

**Comment by NuckChorris** [comment]
I actually added this capability in V3
