### ISSUE TITLE
Question - Looking to make a contribution

### ISSUE THREAD

**Issue by redwire** [hummingbird-me/hummingbird#680]
Hey Hummingbird, folks.
I haven't been using the site in a while but I was thinking recently that it'd be awesome to make a couple contributions to help you guys along.  Could someone inform me of what some potentially low(er) hanging fruit I could reach for?  If you take a look in my project history, you'll see I'm particularly adept at doing backend development and documentation.  If you'd like to discuss an API or something, I think I can really help.
Cheers.

**Comment by JoshFabian** [comment]
Hey Redwire, 

I just sent an invite to our slack dev chat to your email. We're _always_ happy to have more help!
