### ISSUE TITLE
Quick update - canGoForward

### ISSUE THREAD

**Issue by danreeves** [hummingbird-me/hummingbird#683]
There's a bug with the `canGoForward` check in the quick update component, here: https://github.com/hummingbird-me/hummingbird/blob/f031863451e34889a7b6e942ee7ca985ddacb90c/frontend/app/components/quick-update.js#L10

If your `library_entries` is a multiple of 6, so that the last page has 6 items, you can page to an empty set of entries.

![screen shot 2015-10-11 at 20 59 43](https://cloud.githubusercontent.com/assets/1973559/10418711/0fc0cc06-705b-11e5-958d-6f6053bed16e.png)

**Comment by JoshFabian** [comment]
Thanks Dan, we'll be fixing this in the rewrite branch: https://github.com/hummingbird-me/hummingbird/tree/the-future

In the event that you'd like to help contribute when you have time here and there, I'd be happy to invite you to join our slack dev chat!

**Comment by danreeves** [comment]
Sorry, I missed that branch. Yeah, I'd love to join the slack: danr@fffunction.co

**Comment by NuckChorris** [comment]
Closing this as a V2 issue.  Should be fixed in V3, though it may just not be _a thing_ in V3 due to how the QU is in that.
