### ISSUE TITLE
Avatar in Nav bar not loading: 403 response

### ISSUE THREAD

**Issue by kevinwlau** [hummingbird-me/hummingbird#685]
Not sure if backend or frontend problem. Similar icon on personal profile uses `.../thumb/...` while the request for nav bar avatar is `.../thumb_small/...`

**Comment by vevix** [comment]
@kevinwlau Did you create your account with Facebook? We have a long standing issue with our avatar handling code for Facebook avatar imports.

The best way to fix this ATM is to simply re-upload your avatar from your profile.

**Comment by kevinwlau** [comment]
@vevix Yes, re-uploading fixed the problem.
