### ISSUE TITLE
Additional Search function

### ISSUE THREAD

**Issue by violetbrina** [hummingbird-me/hummingbird#689]
Please add the ability to search for subbed/dubbed anime in the search bar and also sort within your library!

**Comment by sachaw** [comment]
I don't believe there is any info in the dB about whether an entry is subbed or dubbed, then again I could be mistaken. we might be able to rip them for mal as they have list of cast for each series including foreign dubs.

**Comment by NuckChorris** [comment]
Will be part of V3 I think
