### ISSUE TITLE
-1 users rated 5

### ISSUE THREAD

**Issue by tenno-seremel** [hummingbird-me/hummingbird#691]
Example: https://hummingbird.me/anime/hoshi-no-umi-no-amuri

Currently at -1 users rated 5…

**Comment by vevix** [comment]
I believe this is due a user getting deleted. /cc @NuckChorris

**Comment by NuckChorris** [comment]
I think it's actually due to the incrementing and decrementing things atomically: there's probably a codepath that causes it to work wrong.

**Comment by NuckChorris** [comment]
Merging this into #707
