### ISSUE TITLE
2015 YiR

### ISSUE THREAD

**Issue by JoshFabian** [hummingbird-me/hummingbird#697]
Data needed:

- New users in 2015
- Hours of anime tracked in 2015 (average per user and as community)
- Hours spent watching most highest rated show of 2015
- Total episodes watched as a community in 2015 
- Total activity feed posts in 2015
- Total forum posts in 2015

- Highest rated tv series (ranked 1 - 10)
- Highest rated movie / ova (ranked 1- 10)
- Worst show of 2015 (ranked 1 - 10)
- Most Overrated show of 2015 (ranked 1 - 10) [high rating, lowish popularity]
- Most under-appreciated show of 2015 (ranked 1 - 10)  [low rating, high popularity]
- Most popular show (ranked 1 - 10)
- Most popular comedy( ranked 1-10)
- Most popular slice of life (ranked 1 - 10)
- Most popular romance (ranked 1 - 10)
- Most popular fantasy (ranked 1 - 10)
- Most popular mecha (ranked 1 - 10)
- Most popular sports (ranked 1 - 10)
- Most popular from winter 2014 - 2015 (ranked 1-10)
- Most popular from spring 2015 (ranked 1 - 10)
- Most popular from summer 2015 (ranked 1 - 10)
- Most popular from fall 2015 (ranked 1-10)

- Highest rated manga (ranked 1 - 10)
- Most popular manga (ranked 1 - 10)
- Most Overrated mange of 2015 (ranked 1 - 10) [high rating, lowish popularity]
- Most under-appreciated manga of 2015 (ranked 1 - 10)  [low rating, high popularity]

**Comment by erengy** [comment]
> - Most overrated [high rating, lowish popularity]
> - Most under-appreciated [low rating, high popularity]

That doesn't sound quite right to me. If something has high ratings but isn't popular, it could very well be a "hidden gem", so to speak. If anything, their calculations should be reversed. In any case though, I think that we'd need another point of reference (e.g. ratings of critics) to be able to determine whether something's overrated or not; we cannot infer that from popularity.

**Comment by JoshFabian** [comment]
Oops, I accidentally got it backwards there.



—
Stay happy, healthy and warm-blooded!

**Comment by sachaw** [comment]
something cool, for the Yir there should be a comparison next to some of the statistics comparing it to yours for example, the average amount of anime track per user within the year could have the amount you have tracked next to it or a percentage diff.

**Comment by NuckChorris** [comment]
Well this is long since done and released, hah
