### ISSUE TITLE
Missing or invalid API key - API v2

### ISSUE THREAD

**Issue by filipecsweb** [hummingbird-me/hummingbird#705]
<p>I'm trying to get data from hummingbrid v2 API, but I get the following message:</p>
<pre>
object(stdClass)#433 (1) {
  ["errors"]=>
  array(1) {
    [0]=>
    object(stdClass)#432 (4) {
      ["title"]=>
      string(62) "Missing or invalid API key; please pass the X-Client-Id header"
      ["details"]=>
      string(151) "Access to APIv2 is restricted to registered applications. Please create an application and pass the unique API key generated as the X-Client-Id header."
      ["href"]=>
      string(32) "https://hummingbird.me/apps/mine"
      ["status"]=>
      string(9) "Forbidden"
    }
  }
}
</pre>

<p>I have the following code in PHP.</p>
<pre>
$url = 'https://hummingbird.me/api/v2/anime/naruto';

$ch = curl_init();

$headers = array(
	'X-Client-Id: Key'
);

curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$output = curl_exec($ch);

curl_close($ch);

$json = json_decode($output);

var_dump($json);
</pre>

<p>When I try with v1 API, it works fine, but I need v2 API, because I need details from the episodes.</p>

<p>Can someone help?</p>
<p>Thanks.</p>

**Comment by wopian** [comment]
```php
$url = 'https://hummingbird.me/api/v2/anime/naruto';

$curl = curl_init();
// Set some options
curl_setopt_array($curl, array(
    CURLOPT_RETURNTRANSFER => 1,
    CURLOPT_URL => $url,
    CURLINFO_HEADER_OUT => 1,
    CURLOPT_HTTPHEADER => ['X-Client-Id: 5040ff07d9deda85e3c3'],
    CURLOPT_USERAGENT => 'App name here' //This line is optional
));
// Send the request & save response
$output = curl_exec($curl);
// Close request to clear up some resources
curl_close($curl);

$json = json_decode($output, true);

print_r($json);
```

**Comment by filipecsweb** [comment]
It worked!

Amazing, thank you so much!

Can you tell why my code did not work?

The only difference I can see is the <code>CURLINFO_HEADER_OUT</code> parameter. Is that so?
