### ISSUE TITLE
/library_entries?user_id=OTHERUSER JSON contains logged in user's is_favorite data

### ISSUE THREAD

**Issue by paz** [hummingbird-me/hummingbird#711]
Is that the intended behavior?

[Source](/hummingbird-me/hummingbird/blob/d3616161ba8f90209f53bbab01b871d8f801c94b/app/controllers/library_entries_controller.rb#L33)

**Comment by NuckChorris** [comment]
I believe is_favorite in the current API reflects the currently logged in user, not the user being viewed. This will make more sense in V3's API I think
