### ISSUE TITLE
Seasonal sorting old animes

### ISSUE THREAD

**Issue by Kokxer** [hummingbird-me/hummingbird#736]
Seasonal Anime sorting gives a clear look, and offers an easy way to find out what to watch next season or what I missed during the past season. Such as Spring 2015; Summer 2015; Fall 2015 ... and so on.

Currently only upcoming are sort by season but old are sort by decade. That causes too many in a tab.

**Comment by wopian** [comment]
[You can sort by year in upcoming V3](https://projects.invisionapp.com/share/3S4CAESCZ#/screens/104358379).

Don't know about seasonal breakdowns though - it may be possible with whatever's in the drop down below the slider.

cc @NuckChorris

**Comment by NuckChorris** [comment]
I don't know if it's in the interface, but we can definitely do this on the server side

cc @joshfabian for design wisdom

**Comment by JoshFabian** [comment]
+1 on seasonal breakdowns in V3.
