### ISSUE TITLE
API v1 Methods Library wiki update

### ISSUE THREAD

**Issue by drabiter** [hummingbird-me/hummingbird#737]
Hi, on V1 Library Remove API it says return `200` for succeeds operation, but apparently it's `201` 

![screenshot from 2016-07-14 09 47 24](https://cloud.githubusercontent.com/assets/2654586/16826587/c1447cd0-49a8-11e6-88af-95dd9029e143.png)

The twist is I accidentally updated upstream wiki instead of mine to correct one :) Please let me know if i need to revert the change.

**Comment by NuckChorris** [comment]
I'm afraid I don't follow.  Can you elaborate what the issue is?

**Comment by drabiter** [comment]
Not issue on the application but the wiki documentation, and then i accidentally updated it. So i'm just asking if that's okay.

**Comment by NuckChorris** [comment]
If the wiki docs were incorrect, there's no issue with fixing it.  It's a wiki, anyone can edit it?

**Comment by drabiter** [comment]
Yup everyone can, in good and bad way. So it's correct I'll leave it as it then.
