### ISSUE TITLE
MyAnimeList DataImporter

### ISSUE THREAD

**Issue by vevix** [hummingbird-me/hummingbird#739]
Noticed some issues when using this tonight.

- Missing case for `PG-13` for `age_rating` - results in `nil`
- Method `subtype` should be `show_type` until a rename actually happens

/cc @NuckChorris @toyhammered

**Comment by toyhammered** [comment]
will fix the first issue for `PG-13`. 
As for the second one there was a conflict with show_type and manga_type. 
`# TODO: removed subtype (show_type, manga_type issue)`, so hopefully Nuck will fix that soon.

**Comment by toyhammered** [comment]
#743

**Comment by NuckChorris** [comment]
@toyhammered in future, you can use `(fixes #743)` in a commit message to have the issue automatically close when the PR gets merged :thumbsup:
