### ISSUE TITLE
Default avatar not rendering in timeline

### ISSUE THREAD

**Issue by markphilpot** [hummingbird-me/hummingbird#742]
![image](https://cloud.githubusercontent.com/assets/46191/16905501/a229d4d4-4c5b-11e6-95cd-fa55dfbd99e2.png)

![image](https://cloud.githubusercontent.com/assets/46191/16905507/b0db1f7e-4c5b-11e6-9a9a-9813fab815af.png)

The extension `.jpg` is appended twice.  Removing the second resolves to the right image.

**Comment by vevix** [comment]
Thanks, this will be fixed in the next deploy.
