### ISSUE TITLE
Add ability to use the API to get all anime objects by genre

### ISSUE THREAD

**Issue by KempfCreative** [hummingbird-me/hummingbird#758]
In order to avoid web and API scraping, I would like to be able to use the API to list anime by more than {id} or {slug}. My particular use case involves pulling all anime by genre, ordered by rating.

If this is possible to do, using either V1 or V2 of the API, what is the expected URI format needed?

If this is not possible to do, is it on the roadmap?

Thank you.

**Comment by NuckChorris** [comment]
API V1 and V2 don't currently provide this, and I don't think we have any APIs for it currently, but it's already doable in V3, our next-gen platform coming hopefully later this year

**Comment by KempfCreative** [comment]
@NuckChorris, thanks so much for the quick reply. I am guessing that V3 isn't publicly accessible?

**Comment by NuckChorris** [comment]
V3 is the next-generation platform, it will be public when it's released later this year
