### ISSUE TITLE
Small user library API Call

### ISSUE THREAD

**Issue by sachaw** [hummingbird-me/hummingbird#759]
Since library calls can be quite large and not ideal to call on a page load, a small library call should be available removing the `anime` element and just leave an `id` for the series, which would allow caching of specific anime json that can be refined as need be without having one massive call.

**Comment by NuckChorris** [comment]
I'm not sure what you're asking for… the ability to load anime data separate from the library data? That's already in V3, and has been since November

**Comment by sachaw** [comment]
yea, just so the user/library call isn't like 200-800kb

**Comment by NuckChorris** [comment]
Makes sense. Yeah, in V3, the client controls all loading of associated objects and so can just not request the anime data. For things it doesn't have cached, it can do a mass load by `filter[id]=1,3,7,8,9,10`

**Comment by sachaw** [comment]
thanks, cant wait for V3.
