### ISSUE TITLE
minimatch issue with docker build of client.

### ISSUE THREAD

**Issue by josephcureton** [hummingbird-me/hummingbird#760]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.

---

**Description:**

_New to hummingbird_ I am trying to install the-future branch via the docker build. I'm erring out at step 8:

`Building client
Step 1 : FROM node:5.9
 ---> 86cbce15c689
Step 2 : MAINTAINER Hummingbird Media, Inc.
 ---> Using cache
 ---> a5d0a1b5d15d
Step 3 : RUN npm install -gq bower
 ---> Using cache
 ---> 40c15966a94b
Step 4 : RUN mkdir -p /opt/hummingbird/client
 ---> Using cache
 ---> f387a983ce7e
Step 5 : COPY ./package.json /opt/hummingbird/client/
 ---> Using cache
 ---> 506a224ef1ab
Step 6 : COPY ./bower.json /opt/hummingbird/client/
 ---> Using cache
 ---> 07845abdb626
Step 7 : WORKDIR /opt/hummingbird/client
 ---> Using cache
 ---> b6915b51e2f9
Step 8 : RUN npm install -q
 ---> Running in 83e8719fdf1a
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
`

 
**Steps to reproduce:**
I am following the setup guide. :

`bin/setup && bin/start`

I am using the latest docker for Mac. 

**Screenshots (if applicable):**

<img width="779" alt="screen shot 2016-08-22 at 4 53 48 pm" src="https://cloud.githubusercontent.com/assets/15135362/17871341/156f6d84-6889-11e6-9c62-a3916146d46f.png">

**OS and Browser:**
 
OSX El Capitan v 10.11.6

**Possible Culprit and Fixes**

Check out this issue:

https://github.com/jshint/jshint/issues/2952

**Comment by NuckChorris** [comment]
This is a warning, not an error.  You can safely ignore it.

**Comment by josephcureton** [comment]
Perfect thanks.
