### ISSUE TITLE
Question related to User Object's waifu_or_husbando

### ISSUE THREAD

**Issue by qgustavor** [hummingbird-me/hummingbird#764]
The [documentation for the User Object](https://github.com/hummingbird-me/hummingbird/wiki/API-v1-Structures#user-object) says:

> `waifu_or_husbando` Can be one of `Waifu`, `Husbando`.

By reading it I assumed this value cannot be different from those two values, but it don't happen for this user: https://hummingbird.me/users/AsterPiano (the value is `The duce`).

What is the intended behavior, allowing any value (as it's stored as a string) or only those two values?

**Comment by wopian** [comment]
It's an unintended loophole from shitty freelancer code ;)

https://hummingbird.me/users/wopian

**Comment by qgustavor** [comment]
Should the documentation be updated with this detail?

**Comment by cybrox** [comment]
I don't think there's much value in that. For now, we are focusing on the future main version, the more time we can put into that instead of fixing/documenting not security relevant mistakes from the past, the better.

If you want to fix/document it, feel free to create a PR, though.

Btw, the commit @wopian referred to is 3ad5943191885a4ddb03f7f4767815197ba3eedc

**Comment by qgustavor** [comment]
Well, if the focus is the new version I think fixing it now isn't important. The documentation is a wiki, so the PR isn't needed, I can just edit it. How about one of those? (I don't know what's the most appropriate)

> `waifu_or_husbando` can be one of `Waifu`, `Husbando` (in some cases, other values).
> `waifu_or_husbando` can be one of `Waifu`, `Husbando`, or other values.
> `waifu_or_husbando` for most users is one of `Waifu`, `Husbando`.

**Comment by matthewdias** [comment]
Well you're not actually _supposed_ to be able to have something else, so maybe best to leave it out of the wiki.

**Comment by NuckChorris** [comment]
The wiki can document the sorry state of our normalization for now, I don't see any problem with that

**Comment by cybrox** [comment]
@qgustavor I added the note from your first suggestion to the wiki. Thanks for mentioning this.
I do agree on that it is no problem to have that stated there and might avoid any confusion if someone is attempting to get (and validate) those values from the API.

Eh, at least we support non-binary concepts, I guess 😉
