### ISSUE TITLE
hummingbird-client fails to build because of invalid characters.

### ISSUE THREAD

**Issue by ibnuda** [hummingbird-me/hummingbird#769]
Hummingbird-client fails to build because of invalid charactes on windows. Apparently caused by broccoli-svg-optimizer.

Steps:
1. Clone the repo.
2. Install the npm and bower dependencies.
3. Serve the application.
4. At the first time loading, will fail like the screencapture below.

![3d278422-acd8-11e6-8313-77457ca7bbbe](https://cloud.githubusercontent.com/assets/8169908/20469593/a55d6180-afd3-11e6-9d7e-873a0099bc4c.PNG)

OS: Windows 7 64 bit.
Browser: IE, Firefox 64 50,  Google Chrome 55.0.2883.52 beta (64-bit)
Node: 7.0.0

**Comment by vevix** [comment]
We really recommend that you setup Hummingbird using docker, it's built with that setup in mind for the development environment.

We have a setup guide over at the [Wiki](https://github.com/hummingbird-me/hummingbird/wiki/Setting-up-a-development-environment#docker-recommended).

**Comment by ibnuda** [comment]
Whelp, didn't know that. Just want to learn ember actually.
Okay. Then this issue will be marked as "won't fix" and will be closed.
Thanks!
