### ISSUE TITLE
API bug

### ISSUE THREAD

**Issue by sachaw** [hummingbird-me/hummingbird#773]
When visiting https://kitsu.io/api/edge/users/:id:
returns JSON for a single user, but when a variable is passed like
https://kitsu.io/api/edge/users/?something=something
returns multiple users
https://kitsu.io/api/edge/users/?somethingelse=somethingelse
not sure if this intentional, but seems wired to me.

**Comment by vevix** [comment]
This is intentional -- Check out the spec that our API uses here: http://jsonapi.org/format/#fetching-resources

**Comment by sachaw** [comment]
Ok, thanks.
