### ISSUE TITLE
Library switches view when updating episode count

### ISSUE THREAD

**Issue by astraldragon** [hummingbird-me/hummingbird#778]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.

---

**Description:** Assuming something isn't properly tracking the AJAX calls going out for the library and it ends up thinking the tab I'm on isn't actually the one I'm on 😄 

**Steps to reproduce:** Open up my library, switch to a tab that takes long to load (for me Completed).  Before that finishes loading, switch to Currently Watching.  Increment an episode count for a show.  Count will update but the view will switch to the previous tabs content (Completed).

**Screenshots (if applicable):**
![bug](https://cloud.githubusercontent.com/assets/846931/21374004/aed6615c-c6f9-11e6-9b62-dd45a0114d03.gif)

**OS and Browser:** Mac Sierra - Chrome 55.0.2883.95

**Comment by vevix** [comment]
Thanks for the report @astraldragon! I'm going to look into this today.

**Comment by astraldragon** [comment]
With the re-brand seems like the project is still open source.  May take a look at learning some Ember 😄

**Comment by cybrox** [comment]
@astraldragon Yeah, staying open source was a very important goal for us, even after the rebrand. Currently, it's mostly @vevix, @JoshFabian and me working on client side. Especially testing needs lots of love after rushing through a lot of things during release, so any contribution is welcome 😄

**Comment by vevix** [comment]
Tests are always welcome 😸!

**Comment by JoshFabian** [comment]
@astraldragon shoot me an email if you'd like to join our dev slack! josh@kitsu.io

**Comment by astraldragon** [comment]
Yeah for sure.  I'll ping you.
