### ISSUE TITLE
Missing translation error/showing Ember data path

### ISSUE THREAD

**Issue by sinthetix** [hummingbird-me/hummingbird#783]
**Description:** 
Found a bug when I was adding one of my favorite animes _Baccano!_  
 
The following text is displayed on some anime/manga resource pages (I noticed two but I wasn't combing for them):

```
Missing translation: media.routes.show.titles.ja_en: 
```

It appears on the Romanized section. It is repeating the Romanized data with an additional missing translation error. The translation does not appear to be missing at all!

**Steps to reproduce:** Go here: https://kitsu.io/anime/steins-gate-episode-23 or here: https://kitsu.io/anime/baccano

**Screenshots:**
<img width="279" alt="screen shot 2017-01-30 at 10 18 56 pm" src="https://cloud.githubusercontent.com/assets/5157195/22451175/2ceed9ec-e73a-11e6-9270-8ce59f040aa1.png">
<img width="317" alt="screen shot 2017-01-30 at 10 22 38 pm" src="https://cloud.githubusercontent.com/assets/5157195/22451231/b3efe440-e73a-11e6-9516-9efdf00e25db.png">

**OS and Browser:** OS X 10.10.5, Google Chrome Version 55.0.2883.95 (64-bit)

**Comment by vevix** [comment]
Thanks! We are planning to clean these up. /cc @NuckChorris

**Comment by sinthetix** [comment]
@NuckChorris fixed it!

<img width="368" alt="screen shot 2017-01-31 at 5 59 32 pm" src="https://cloud.githubusercontent.com/assets/5157195/22491434/5da5dd9e-e7f1-11e6-8d38-3f1ff3eb1c77.png">

Closing this. Good work! 😄
