### ISSUE TITLE
Suggestion: Shorter router.

### ISSUE THREAD

**Issue by indrakaw** [hummingbird-me/hummingbird#788]
Shorter router for shorter url. Here my suggestions:

User:
`https://kitsu.io/users/josh` -> `https://kitsu.io/u/josh`

Manga:
`https://kitsu.io/manga/shingeki-no-kyojin` -> `https://kitsu.io/m/shingeki-no-kyojin`

Anime:
`https://kitsu.io/anime/sword-art-online` -> `https://kitsu.io/a/sword-art-online`

Real-life example:
`https://www.youtube.com/c/github` for `https://www.youtube.com/user/github`

**Comment by indrakaw** [comment]
You don't have to change it. Use it as redirection. e.g. `https://kitsu.io/u/josh` will redirect to `https://kitsu.io/users/josh`

**Comment by vevix** [comment]
We actually did these shortened versions on Hummingbird, I'm not sure how many people made use of them but I'm not sold that we need to do it now.

In what scenario would you need to use these shorter links over the default or a service like https://bit.ly

**Comment by trmcnvn** [comment]
Probably not going to do this in the near-future. We've talked before about a shorter URL over `kitsu.io` but we'll see how that pans out. :heart:
