### ISSUE TITLE
How to access dashboard? What is the url?

### ISSUE THREAD

**Issue by samuelboanly** [hummingbird-me/hummingbird#789]
Thank you for taking the time to open an issue!

For bug reports please include the following section in your issue details.

---

**Description:**

**Steps to reproduce:**

**Screenshots (if applicable):**

**OS and Browser:**

**Comment by NuckChorris** [comment]
Hi there, could you elaborate on what your issue is?  If you're looking for the site, it's https://kitsu.io/ :)

**Comment by samuelboanly** [comment]
Admin url for kitsu.io to access theyr dashboard

**Comment by JoshFabian** [comment]
I'm assuming you mean to access the dashboard on your local machine (as normal users cannot access it in production... for obvious reasons)

The url is: https://kitsu.io/admin

**Comment by wopian** [comment]
To access your groups dashboard, either click the Dashboard button below the group name on group pages, or go to kitsu.io/groups/yourgroupnamehere/dashboard 👍
