### ISSUE TITLE
Unable to login: forums.hummingbird.me

### ISSUE THREAD

**Issue by gopherfortress** [hummingbird-me/hummingbird#790]
**Description:** I tried to post a question on https://forums.hummingbird.me/t/kitsu-api-documentation/33367 but I cannot login. It goes to:
* https://kitsu.io/discourse/sso?sso=bm9uY2U9MGJiNjJjZjM5MjdlMjc3ZTY0ZDJmMDE3NzFhMzMyODEmcmV0dXJu%0AX3Nzb191cmw9aHR0cHMlM0ElMkYlMkZmb3J1bXMuaHVtbWluZ2JpcmQubWUl%0AMkZzZXNzaW9uJTJGc3NvX2xvZ2lu%0A&sig=19d978c9a94fe6947bc0405e2c4acdef412178072da5369dba2d2e4799a55fb6#from-hummingbird
* https://kitsu.io/404

My kitsu account is: gopherfortress

**Steps to reproduce:** Go to https://forums.hummingbird.me/t/kitsu-api-documentation/33367 then click Log In.

**Screenshots (if applicable):**

**OS and Browser:**
Windows and Chrome

**Comment by wopian** [comment]
The forums are in read-only mode and will soon be archived.

Although it is still possible to post if you haven't logged out.
