### ISSUE TITLE
Unable to find a converter

### ISSUE THREAD

**Issue by PedBerTor** [hummingbird-me/hummingbird#793]
We i do get to kitsu i receive a null object. This is what i have in the console:

ADVICE: Unable to find a converter for this representation : [application/vnd.api+json]

Any solution? Thanks

**Comment by cybrox** [comment]
This seems to be an issue with the library you are using for parsing the response, not with the Kitsu API itself. I assume the library does not provide a default implementation (or does not know how to map) for the given data type (`application/vnd.api+json`) you expect and thus wants you to provide a custom converter.

Feel free to re-open this issue if I am wrong.
