### ISSUE TITLE
Client doesn't access to the database with clean install

### ISSUE THREAD

**Issue by hmsintrepide** [hummingbird-me/hummingbird#797]
**Description:**
With a clean installation, with or without manual installation of database data, kitsu client does not access to the database. I see some pending migration errors in logs.

**Steps to reproduce:**
Clean install from hummingbird-me repository

**Screenshots (if applicable):**
With my repo
![capture d ecran de 2017-07-09 17-25-07](https://user-images.githubusercontent.com/934201/27995280-9828f918-64cb-11e7-9bf5-986dca2e8be1.png)

With official repo
![capture d ecran de 2017-07-09 17-36-51](https://user-images.githubusercontent.com/934201/27995360-3db13f34-64cd-11e7-82c1-74667739901d.png)

**OS and Browser:**
Server: Ubuntu 16.04.2 LTS
Client: Fedora 25 with Chromium 59

[server_logs.txt](https://github.com/hummingbird-me/hummingbird/files/1133849/server_logs.txt)
[seed_reset_logs.txt](https://github.com/hummingbird-me/hummingbird/files/1133853/seed_reset_logs.txt)
[postgres_database_lists.txt](https://github.com/hummingbird-me/hummingbird/files/1133861/postgres_database_lists.txt)

**Comment by toyhammered** [comment]
ok just fixed it! (or actually found a way to make it work)
```
bin/stop; bin/rake db:drop db:create; bin/seed; bin/rake db:migrate; bin/rake db:migrate:up VERSION=20170607055017; bin/rake db:migrate; bin/restart
```

**Comment by hmsintrepide** [comment]
thanks
work for me too
