### ISSUE TITLE
Suggestion: Rating design

### ISSUE THREAD

**Issue by sachaw** [hummingbird-me/hummingbird#799]
I love the 20 point rating system, but the slider is horrible, A suggestion, for list entries have an inline expanding slider, this can also work elsewhere but here is an example:
![kitsu](https://user-images.githubusercontent.com/11172820/28660334-ab2d1d94-72f1-11e7-97ea-ebcd2a4f482a.gif)

**Comment by JoshFabian** [comment]
Hm, this really isn't bad. We'll definitely want to work on making the slider soon!

**Comment by trmcnvn** [comment]
I like this! but I think this is something better suited for our Feature Request board?

**Comment by sachaw** [comment]
I made a feature request: https://kitsu.io/feedback/feature-requests/p/redesign-rating-slider
