### ISSUE TITLE
Error 502 when running localhost:32769

### ISSUE THREAD

**Issue by agungtsp** [hummingbird-me/hummingbird#801]
after all installation completed and run bin/start , error code is 502 on nginx, how to fix that ? 

I already check nginx.conf and nothings wrong

**Comment by matthewdias** [comment]
If the client hasn't finished building yet you will get this error. You can check if it's done by running `bin/logs -f client`. It should have some output telling you the build is complete when it finishes.

**Comment by agungtsp** [comment]
after run bin/logs -f client:

Attaching to hummingbird_client_1
client_1         | Could not start watchman
client_1         | Visit https://ember-cli.com/user-guide/#watchman for more info.
client_1         | ember-cli-sentry will not be loaded from bower installation

**Comment by matthewdias** [comment]
You can ignore those messages. Let it continue to run, it takes quite a while the first time.

**Comment by agungtsp** [comment]
but keep error 502 when access localhost:32769

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.9.15</center>
</body>
</html>

**Comment by agungtsp** [comment]
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

**Comment by matthewdias** [comment]
Try increasing that timeout.

**Comment by agungtsp** [comment]
Result keep 502 error nginx. 

Have you step by step documentation to install this or  create new for us? 

I'm already follow guide from your wiki but keep 502.  I'm try it for 5 days :D

**Comment by matthewdias** [comment]
have you waited until you see the build complete? it should look like the following when it's done
```
client_1         | Could not start watchman
client_1         | Visit https://ember-cli.com/user-guide/#watchman for more info.
client_1         | ember-cli-sentry will not be loaded from bower installation
client_1         | Livereload server on http://localhost:57777
client_1         | tmp/rollup-cache_path-IwKyUjgY.tmp/exports/es6/metal/queue.js (11:16) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
client_1         | tmp/rollup-cache_path-IwKyUjgY.tmp/exports/es6/metal/queue.js (11:24) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
client_1         | tmp/rollup-cache_path-IwKyUjgY.tmp/exports/es6/metal/scheduler.js (11:16) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
client_1         | tmp/rollup-cache_path-IwKyUjgY.tmp/exports/es6/metal/scheduler.js (11:24) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
client_1         | Warning: ignoring input sourcemap for vendor/ember/ember.debug.js because ENOENT: no such file or directory, open '/opt/kitsu/client/tmp/source_map_concat-input_base_path-jL0wAzrO.tmp/vendor/ember/ember.debug.map'
client_1         | Warning: ignoring input sourcemap for vendor/ember/ember-testing.js because ENOENT: no such file or directory, open '/opt/kitsu/client/tmp/source_map_concat-input_base_path-98W0LzCr.tmp/vendor/ember/ember-testing.map'
client_1         | 
client_1         | Build successful (23193ms) – Serving on http://localhost:80/
client_1         | 
client_1         | 
client_1         | 
client_1         | Slowest Nodes (totalTime => 5% )              | Total (avg)         
client_1         | ----------------------------------------------+---------------------
client_1         | EslintValidationFilter (4)                    | 7551ms (1887 ms)    
client_1         | Babel (94)                                    | 3238ms (34 ms)      
client_1         | Concat (10)                                   | 1903ms (190 ms)     
client_1         | PostcssFilter (1)                             | 1668ms              
client_1         | SassCompiler (3)                              | 1536ms (512 ms)     
client_1         | TemplateCompiler (17)                         | 1236ms (72 ms)      
client_1         | 
```
If you don't see that yet, let it continue to run until it finishes. The logs you already pasted indicate you've followed the steps correctly up to this point. If you try to access the app before you see this, you'll get a 502.

**Comment by agungtsp** [comment]
Oke Thanks, I'm failed to develop this

**Comment by Marcozero2** [comment]
I'm so tired of this that O really don't Care anymore.
Whatever...

Em 30 de jul de 2017 21:41, "Agung Trilaksono SP" <notifications@github.com>
escreveu:
