### ISSUE TITLE
Edit Library Entry buttons off-screen in firefox

### ISSUE THREAD

**Issue by RX14** [hummingbird-me/hummingbird#802]
In Firefox, the right-aligned buttons in the "Progress" and "Rewatch Count" boxes are not aligned with the right of the container, and overflow. In Chrome, this does not happen.

Example:
![](https://my.mixtape.moe/qatgoi.png)

To reproduce, visit an [anime page](https://kitsu.io/anime/made-in-abyss) for an anime you are watching, while signed in to kitsu on Firefox, and click the "Edit Library Entry" link underneath the poster image.

**Comment by JayFischer** [comment]
Not able to reproduce, looks to be a very old open issue.  Do you have the Firefox version you tested on?

Tested on 65.0, 55.0, 43.0 and got [expected](https://user-images.githubusercontent.com/17351072/55133145-a14d0d80-50f2-11e9-8462-434e6a04c4ef.png).
