### ISSUE TITLE
Update bad urls on README & CONTRIBUTING

### ISSUE THREAD

**Issue by JayFischer** [hummingbird-me/hummingbird#804]
**Description:**
There are several links on the README and CONTRIBUTING that link to the hummingbird domain. It seems this domain is no longer is in use and redirects to an unexpected/unwanted page (Ads or failed connection).

README [Link](https://github.com/hummingbird-me/hummingbird/tree/the-future#contributing)

> If you have any questions don't hesitate to contact us! Feel free to create a in the [forum dev category](http://forums.hummingbird.me/category/dev) or email Josh to get access to our Slack.

Not sure if there is a alternative link? Maybe remove link?

> Please don't use Github issues for feature requests, instead create a topic in [the forum feedback category](http://forums.hummingbird.me/category/feedback).

Update link to `https://kitsu.io/feedback/feature-requests`

CONTRIBUTING [Link](https://github.com/hummingbird-me/hummingbird/blob/the-future/.github/CONTRIBUTING.md)
>You can submit bug reports by creating an issue on GitHub or by creating a thread on our [forums.](https://forums.hummingbird.me/c/feedback/bugs)

Update link to `https://kitsu.io/feedback/bugs`

Since it would be a quick change, maybe we should update to the respective Kitsu urls if applicable, otherwise remove?

edit1: fixed links to `the-future` branch

**Comment by wopian** [comment]
That's the master branch which is an archive of Hummingbird V1 & V2. `the-future` is the (default) branch for Kitsu

**Comment by JayFischer** [comment]
I pasted the wrong links (now updated above) but I do believe these invalid links are on `the-future` branch as well.

**Comment by wopian** [comment]
Fixed the links on `the-future` branch 👍
