### ISSUE TITLE
Library sorting parameters inconsistently applied on page load

### ISSUE THREAD

**Issue by awused** [hummingbird-me/hummingbird#805]
**Description:**

Sorting parameters for libraries are not consistently applied on page load or refresh.

I've seen two major problems:

1- For both anime and manga the direction url parameter ("direction=asc") is never respected. Sorting on page load is always in descending order.

2- For manga, but not anime, some sorting options aren't applied on page load. Attempting to sort by length, title, or date updated will not persist after a refresh.

**Steps to reproduce:**

Go to your library
Sort your manga by title, ascending or descending
Refresh the page
Observe that the list is now using the default order

Sorting anime by length ascending will result in anime sorted by length descending

**Screenshots (if applicable):**

library?media=manga&sort=title&status=current
https://i.imgur.com/tJL48FE.png

**OS and Browser:**
Windows 10, Firefox and Chrome

**Comment by resolritter** [comment]
1. I do not see how to activate that query parameter ("direction=asc"). Has that been removed?

2. On my end, those sorting parameters are respected on page refreshes

**Comment by matthewdias** [comment]
You can click the arrow here to change direction 
![image](https://user-images.githubusercontent.com/3302524/66723672-79e53600-ede1-11e9-8999-28cc3b00cde8.png)

I can reproduce the issues described here.

**Comment by matthewdias** [comment]
moved to canny since we use that for bug tracking. Please make future bug reports there. https://kitsu.canny.io/bugs/p/library-sorting-parameters-inconsistently-applied-on-page-load
