### ISSUE TITLE
Character Page Links

### ISSUE THREAD

**Issue by ALEXANDERB82** [hummingbird-me/hummingbird#808]
On the Character tab for specific Anime such as One Piece, the character names and images are set up to function as links however they don't lead to anywhere. I think your website would benefit from having a page for each character set up for each of those links. These pages could maybe include a description of the characters and their roles in the show.

**Comment by NuckChorris** [comment]
Hey, sorry for the slow reply!  We don't really use GitHub for feature requests, they're in our [Canny Feature Requests database](https://kitsu.io/feedback/feature-requests).

Looks like there's already a few people asking for Character pages (not surprising, they're something we have had planned for a long time!), such as [this one](https://kitsu.io/feedback/feature-requests/p/add-functionality-to-character-pages)
