### ISSUE TITLE
Buggy dashboard menu

### ISSUE THREAD

**Issue by lauderandtaiga** [hummingbird-me/hummingbird#92]
Whenever I'm not logged in, on forums.hummingbird.me the dashboard menupoint does nothing. After changing to another menue point, the dashboard works.

**Comment by cybrox** [comment]
We might want to finally update the forum header, now that Discourse is more or less stable.
Thoughts?

**Comment by JoshFabian** [comment]
Probably a good idea, but definitely low priority. Forum activity is restricted to a fairly small subset of the community and I have a feeling that number will decrease further with the release of group functionality.
